import org.apache.spark.sql.SparkSession

//Author - Michał Bis, Statistics Poland

object FF_reference_frame extends App {
  val spark = SparkSession.builder
    //.master("yarn-client")
    .master("local[*]")
    .appName("Fishing Fleet")
    .getOrCreate()
  spark.sparkContext.setLogLevel("ERROR")

  // ** datasource source ** EC-Data-Platform

  //mmsi,imo,name,callsign,destination,draught,dim_a,dim_b,dim_c,dim_c,type_and_cargo,timestamp
  val df_messages = spark.read.options(Map("inferSchema" -> "true", "delimiter" -> ",", "header" -> "true")).csv("hdfs:///user/hadoop/AIS/Messages/2016*.csv.gz")

  val df_messages_fishing = df_messages.filter("type_and_cargo == '30'") //Fishing

  //Spark SQL
  df_messages_fishing.createOrReplaceTempView("EMP")

  val df_fishing_fleet_country_origin = spark.sql("select emp.mmsi, emp.imo, emp.name, emp.callsign, " +
    "CASE\n  " +
    "WHEN substr(mmsi, 1, 3)='201'\tTHEN 'Albania'\n" +
    "WHEN substr(mmsi, 1, 3)='202'\tTHEN 'Andorra'\n  " +
    "WHEN substr(mmsi, 1, 3)='203'\tTHEN 'Austria'\n  " +
    "WHEN substr(mmsi, 1, 3)='204'\tTHEN 'Portugal'\n  " +
    "WHEN substr(mmsi, 1, 3)='205'\tTHEN 'Belgium'\n  " +
    "WHEN substr(mmsi, 1, 3)='206'\tTHEN 'Belarus'\n  " +
    "WHEN substr(mmsi, 1, 3)='207'\tTHEN 'Bulgaria'\n  " +
    "WHEN substr(mmsi, 1, 3)='208'\tTHEN 'Vatican'\n  " +
    "WHEN substr(mmsi, 1, 3)='209'\tTHEN 'Cyprus'\n  " +
    "WHEN substr(mmsi, 1, 3)='210'\tTHEN 'Cyprus'\n  " +
    "WHEN substr(mmsi, 1, 3)='211'\tTHEN 'Germany'\n  " +
    "WHEN substr(mmsi, 1, 3)='212'\tTHEN 'Cyprus'\n  " +
    "WHEN substr(mmsi, 1, 3)='213'\tTHEN 'Georgia'\n  " +
    "WHEN substr(mmsi, 1, 3)='214'\tTHEN 'Moldova'\n  " +
    "WHEN substr(mmsi, 1, 3)='215'\tTHEN 'Malta'\n  " +
    "WHEN substr(mmsi, 1, 3)='216'\tTHEN 'Armenia'\n  " +
    "WHEN substr(mmsi, 1, 3)='218'\tTHEN 'Germany'\n  " +
    "WHEN substr(mmsi, 1, 3)='219'\tTHEN 'Denmark'\n  " +
    "WHEN substr(mmsi, 1, 3)='220'\tTHEN 'Denmark'\n  " +
    "WHEN substr(mmsi, 1, 3)='224'\tTHEN 'Spain'\n  " +
    "WHEN substr(mmsi, 1, 3)='225'\tTHEN 'Spain'\n  " +
    "WHEN substr(mmsi, 1, 3)='226'\tTHEN 'France'\n  " +
    "WHEN substr(mmsi, 1, 3)='227'\tTHEN 'France'\n  " +
    "WHEN substr(mmsi, 1, 3)='228'\tTHEN 'France'\n  " +
    "WHEN substr(mmsi, 1, 3)='229'\tTHEN 'Malta'\n  " +
    "WHEN substr(mmsi, 1, 3)='230'\tTHEN 'Finland'\n  " +
    "WHEN substr(mmsi, 1, 3)='231'\tTHEN 'Faroe Is'\n  " +
    "WHEN substr(mmsi, 1, 3)='232'\tTHEN 'United Kingdom'\n  " +
    "WHEN substr(mmsi, 1, 3)='233'\tTHEN 'United Kingdom'\n  " +
    "WHEN substr(mmsi, 1, 3)='234'\tTHEN 'United Kingdom'\n  " +
    "WHEN substr(mmsi, 1, 3)='235'\tTHEN 'United Kingdom'\n  " +
    "WHEN substr(mmsi, 1, 3)='236'\tTHEN 'Gibraltar'\n  " +
    "WHEN substr(mmsi, 1, 3)='237'\tTHEN 'Greece'\n  " +
    "WHEN substr(mmsi, 1, 3)='238'\tTHEN 'Croatia'\n  " +
    "WHEN substr(mmsi, 1, 3)='239'\tTHEN 'Greece'\n  " +
    "WHEN substr(mmsi, 1, 3)='240'\tTHEN 'Greece'\n  " +
    "WHEN substr(mmsi, 1, 3)='241'\tTHEN 'Greece'\n  " +
    "WHEN substr(mmsi, 1, 3)='242'\tTHEN 'Morocco'\n  " +
    "WHEN substr(mmsi, 1, 3)='243'\tTHEN 'Hungary'\n  " +
    "WHEN substr(mmsi, 1, 3)='244'\tTHEN 'Netherlands'\n  " +
    "WHEN substr(mmsi, 1, 3)='245'\tTHEN 'Netherlands'\n  " +
    "\WHEN substr(mmsi, 1, 3)='246'\tTHEN 'Netherlands'\n  " +
    "WHEN substr(mmsi, 1, 3)='247'\tTHEN 'Italy'\n  " +
    "WHEN substr(mmsi, 1, 3)='248'\tTHEN 'Malta'\n  " +
    "WHEN substr(mmsi, 1, 3)='249'\tTHEN 'Malta'\n  " +
    "WHEN substr(mmsi, 1, 3)='250'\tTHEN 'Ireland'\n  " +
    "WHEN substr(mmsi, 1, 3)='251'\tTHEN 'Iceland'\n  " +
    "WHEN substr(mmsi, 1, 3)='252'\tTHEN 'Liechtenstein'\n  " +
    "WHEN substr(mmsi, 1, 3)='253'\tTHEN 'Luxembourg'\n  " +
    "WHEN substr(mmsi, 1, 3)='254'\tTHEN 'Monaco'\n  " +
    "WHEN substr(mmsi, 1, 3)='255'\tTHEN 'Portugal'\n  " +
    "WHEN substr(mmsi, 1, 3)='256'\tTHEN 'Malta'\n  " +
    "WHEN substr(mmsi, 1, 3)='257'\tTHEN 'Norway'\n  " +
    "WHEN substr(mmsi, 1, 3)='258'\tTHEN 'Norway'\n  " +
    "WHEN substr(mmsi, 1, 3)='259'\tTHEN 'Norway'\n  " +
    "WHEN substr(mmsi, 1, 3)='261'\tTHEN 'Poland'\n  " +
    "WHEN substr(mmsi, 1, 3)='262'\tTHEN 'Montenegro'\n  " +
    "WHEN substr(mmsi, 1, 3)='263'\tTHEN 'Portugal'\n  " +
    "WHEN substr(mmsi, 1, 3)='264'\tTHEN 'Romania'\n  " +
    "WHEN substr(mmsi, 1, 3)='265'\tTHEN 'Sweden'\n  " +
    "WHEN substr(mmsi, 1, 3)='266'\tTHEN 'Sweden'\n  " +
    "WHEN substr(mmsi, 1, 3)='267'\tTHEN 'Slovakia'\n  " +
    "WHEN substr(mmsi, 1, 3)='268'\tTHEN 'San Marino'\n  " +
    "WHEN substr(mmsi, 1, 3)='269'\tTHEN 'Switzerland'\n  " +
    "WHEN substr(mmsi, 1, 3)='270'\tTHEN 'Czech Republic'\n  " +
    "WHEN substr(mmsi, 1, 3)='271'\tTHEN 'Turkey'\n  " +
    "WHEN substr(mmsi, 1, 3)='272'\tTHEN 'Ukraine'\n  " +
    "WHEN substr(mmsi, 1, 3)='273'\tTHEN 'Russia'\n  " +
    "WHEN substr(mmsi, 1, 3)='274'\tTHEN 'FYR Macedonia'\n  " +
    "WHEN substr(mmsi, 1, 3)='275'\tTHEN 'Latvia'\n  " +
    "WHEN substr(mmsi, 1, 3)='276'\tTHEN 'Estonia'\n  " +
    "WHEN substr(mmsi, 1, 3)='277'\tTHEN 'Lithuania'\n  " +
    "WHEN substr(mmsi, 1, 3)='278'\tTHEN 'Slovenia'\n  " +
    "WHEN substr(mmsi, 1, 3)='279'\tTHEN 'Serbia'\n  " +
    "WHEN substr(mmsi, 1, 3)='301'\tTHEN 'Anguilla'\n  " +
    "WHEN substr(mmsi, 1, 3)='303'\tTHEN 'USA'\n  " +
    "WHEN substr(mmsi, 1, 3)='304'\tTHEN 'Antigua Barbuda'\n  " +
    "WHEN substr(mmsi, 1, 3)='305'\tTHEN 'Antigua Barbuda'\n  " +
    "WHEN substr(mmsi, 1, 3)='306'\tTHEN 'Curacao'\n  " +
    "WHEN substr(mmsi, 1, 3)='307'\tTHEN 'Aruba'\n  " +
    "WHEN substr(mmsi, 1, 3)='308'\tTHEN 'Bahamas'\n  " +
    "WHEN substr(mmsi, 1, 3)='309'\tTHEN 'Bahamas'\n  " +
    "WHEN substr(mmsi, 1, 3)='310'\tTHEN 'Bermuda'\n  " +
    "WHEN substr(mmsi, 1, 3)='311'\tTHEN 'Bahamas'\n  " +
    "WHEN substr(mmsi, 1, 3)='312'\tTHEN 'Belize'\n  " +
    "WHEN substr(mmsi, 1, 3)='314'\tTHEN 'Barbados'\n  " +
    "WHEN substr(mmsi, 1, 3)='316'\tTHEN 'Canada'\n  " +
    "WHEN substr(mmsi, 1, 3)='319'\tTHEN 'Cayman Is'\n  " +
    "WHEN substr(mmsi, 1, 3)='321'\tTHEN 'Costa Rica'\n  " +
    "WHEN substr(mmsi, 1, 3)='323'\tTHEN 'Cuba'\n  " +
    "WHEN substr(mmsi, 1, 3)='325'\tTHEN 'Dominica'\n  " +
    "WHEN substr(mmsi, 1, 3)='327'\tTHEN 'Dominican Rep'\n  " +
    "WHEN substr(mmsi, 1, 3)='329'\tTHEN 'Guadeloupe'\n  " +
    "WHEN substr(mmsi, 1, 3)='330'\tTHEN 'Grenada'\n  " +
    "WHEN substr(mmsi, 1, 3)='331'\tTHEN 'Greenland'\n  " +
    "WHEN substr(mmsi, 1, 3)='332'\tTHEN 'Guatemala'\n  " +
    "WHEN substr(mmsi, 1, 3)='334'\tTHEN 'Honduras'\n  " +
    "WHEN substr(mmsi, 1, 3)='336'\tTHEN 'Haiti'\n  " +
    "WHEN substr(mmsi, 1, 3)='338'\tTHEN 'USA'\n  " +
    "WHEN substr(mmsi, 1, 3)='339'\tTHEN 'Jamaica'\n  " +
    "WHEN substr(mmsi, 1, 3)='341'\tTHEN 'St Kitts Nevis'\n  " +
    "WHEN substr(mmsi, 1, 3)='343'\tTHEN 'St Lucia'\n  " +
    "WHEN substr(mmsi, 1, 3)='345'\tTHEN 'Mexico'\n  " +
    "WHEN substr(mmsi, 1, 3)='347'\tTHEN 'Martinique'\n  " +
    "WHEN substr(mmsi, 1, 3)='348'\tTHEN 'Montserrat'\n  " +
    "WHEN substr(mmsi, 1, 3)='350'\tTHEN 'Nicaragua'\n  " +
    "WHEN substr(mmsi, 1, 3)='351'\tTHEN 'Panama'\n  " +
    "WHEN substr(mmsi, 1, 3)='352'\tTHEN 'Panama'\n  " +
    "WHEN substr(mmsi, 1, 3)='353'\tTHEN 'Panama'\n  " +
    "WHEN substr(mmsi, 1, 3)='354'\tTHEN 'Panama'\n  " +
    "WHEN substr(mmsi, 1, 3)='355'\tTHEN 'Panama'\n  " +
    "WHEN substr(mmsi, 1, 3)='356'\tTHEN 'Panama'\n  " +
    "WHEN substr(mmsi, 1, 3)='357'\tTHEN 'Panama'\n  " +
    "WHEN substr(mmsi, 1, 3)='358'\tTHEN 'Puerto Rico'\n  " +
    "WHEN substr(mmsi, 1, 3)='359'\tTHEN 'El Salvador'\n  " +
    "WHEN substr(mmsi, 1, 3)='361'\tTHEN 'St Pierre Miquelon'\n  " +
    "WHEN substr(mmsi, 1, 3)='362'\tTHEN 'Trinidad Tobago'\n  " +
    "WHEN substr(mmsi, 1, 3)='364'\tTHEN 'Turks Caicos Is'\n  " +
    "WHEN substr(mmsi, 1, 3)='366'\tTHEN 'USA'\n  " +
    "WHEN substr(mmsi, 1, 3)='367'\tTHEN 'USA'\n  " +
    "WHEN substr(mmsi, 1, 3)='368'\tTHEN 'USA'\n  " +
    "WHEN substr(mmsi, 1, 3)='369'\tTHEN 'USA'\n  " +
    "WHEN substr(mmsi, 1, 3)='370'\tTHEN 'Panama'\n  " +
    "WHEN substr(mmsi, 1, 3)='371'\tTHEN 'Panama'\n  " +
    "WHEN substr(mmsi, 1, 3)='372'\tTHEN 'Panama'\n  " +
    "WHEN substr(mmsi, 1, 3)='373'\tTHEN 'Panama'\n  " +
    "WHEN substr(mmsi, 1, 3)='374'\tTHEN 'Panama'\n  " +
    "WHEN substr(mmsi, 1, 3)='375'\tTHEN 'St Vincent Grenadines'\n  " +
    "WHEN substr(mmsi, 1, 3)='376'\tTHEN 'St Vincent Grenadines'\n  " +
    "WHEN substr(mmsi, 1, 3)='377'\tTHEN 'St Vincent Grenadines'\n  " +
    "WHEN substr(mmsi, 1, 3)='378'\tTHEN 'British Virgin Is'\n  " +
    "WHEN substr(mmsi, 1, 3)='379'\tTHEN 'US Virgin Is'\n  " +
    "WHEN substr(mmsi, 1, 3)='401'\tTHEN 'Afghanistan'\n  " +
    "WHEN substr(mmsi, 1, 3)='403'\tTHEN 'Saudi Arabia'\n  " +
    "WHEN substr(mmsi, 1, 3)='405'\tTHEN 'Bangladesh'\n  " +
    "WHEN substr(mmsi, 1, 3)='408'\tTHEN 'Bahrain'\n  " +
    "WHEN substr(mmsi, 1, 3)='410'\tTHEN 'Bhutan'\n  " +
    "WHEN substr(mmsi, 1, 3)='412'\tTHEN 'China'\n  " +
    "WHEN substr(mmsi, 1, 3)='413'\tTHEN 'China'\n  " +
    "WHEN substr(mmsi, 1, 3)='414'\tTHEN 'China'\n  " +
    "WHEN substr(mmsi, 1, 3)='416'\tTHEN 'Taiwan'\n  " +
    "WHEN substr(mmsi, 1, 3)='417'\tTHEN 'Sri Lanka'\n  " +
    "WHEN substr(mmsi, 1, 3)='419'\tTHEN 'India'\n  " +
    "WHEN substr(mmsi, 1, 3)='422'\tTHEN 'Iran'\n  " +
    "WHEN substr(mmsi, 1, 3)='423'\tTHEN 'Azerbaijan'\n  " +
    "WHEN substr(mmsi, 1, 3)='425'\tTHEN 'Iraq'\n  " +
    "WHEN substr(mmsi, 1, 3)='428'\tTHEN 'Israel'\n  " +
    "WHEN substr(mmsi, 1, 3)='431'\tTHEN 'Japan'\n  " +
    "WHEN substr(mmsi, 1, 3)='432'\tTHEN 'Japan'\n  " +
    "WHEN substr(mmsi, 1, 3)='434'\tTHEN 'Turkmenistan'\n  " +
    "WHEN substr(mmsi, 1, 3)='436'\tTHEN 'Kazakhstan'\n  " +
    "WHEN substr(mmsi, 1, 3)='437'\tTHEN 'Uzbekistan'\n  " +
    "WHEN substr(mmsi, 1, 3)='438'\tTHEN 'Jordan'\n  " +
    "WHEN substr(mmsi, 1, 3)='440'\tTHEN 'Korea'\n  " +
    "WHEN substr(mmsi, 1, 3)='441'\tTHEN 'Korea'\n  " +
    "WHEN substr(mmsi, 1, 3)='443'\tTHEN 'Palestine'\n  " +
    "WHEN substr(mmsi, 1, 3)='445'\tTHEN 'DPR Korea'\n  " +
    "WHEN substr(mmsi, 1, 3)='447'\tTHEN 'Kuwait'\n  " +
    "WHEN substr(mmsi, 1, 3)='450'\tTHEN 'Lebanon'\n  " +
    "WHEN substr(mmsi, 1, 3)='451'\tTHEN 'Kyrgyz Republic'\n  " +
    "WHEN substr(mmsi, 1, 3)='453'\tTHEN 'Macao'\n  " +
    "WHEN substr(mmsi, 1, 3)='455'\tTHEN 'Maldives'\n  " +
    "WHEN substr(mmsi, 1, 3)='457'\tTHEN 'Mongolia'\n  " +
    "WHEN substr(mmsi, 1, 3)='459'\tTHEN 'Nepal'\n  " +
    "WHEN substr(mmsi, 1, 3)='461'\tTHEN 'Oman'\n  " +
    "WHEN substr(mmsi, 1, 3)='463'\tTHEN 'Pakistan'\n  " +
    "WHEN substr(mmsi, 1, 3)='466'\tTHEN 'Qatar'\n  " +
    "WHEN substr(mmsi, 1, 3)='468'\tTHEN 'Syria'\n  " +
    "WHEN substr(mmsi, 1, 3)='470'\tTHEN 'UAE'\n  " +
    "WHEN substr(mmsi, 1, 3)='472'\tTHEN 'Tajikistan'\n  " +
    "WHEN substr(mmsi, 1, 3)='473'\tTHEN 'Yemen'\n  " +
    "WHEN substr(mmsi, 1, 3)='475'\tTHEN 'Yemen'\n  " +
    "WHEN substr(mmsi, 1, 3)='477'\tTHEN 'Hong Kong'\n  " +
    "WHEN substr(mmsi, 1, 3)='478'\tTHEN 'Bosnia and Herzegovina'\n  " +
    "WHEN substr(mmsi, 1, 3)='501'\tTHEN 'Antarctica'\n  " +
    "WHEN substr(mmsi, 1, 3)='503'\tTHEN 'Australia'\n  " +
    "WHEN substr(mmsi, 1, 3)='506'\tTHEN 'Myanmar'\n  " +
    "WHEN substr(mmsi, 1, 3)='508'\tTHEN 'Brunei'\n  " +
    "WHEN substr(mmsi, 1, 3)='510'\tTHEN 'Micronesia'\n  " +
    "WHEN substr(mmsi, 1, 3)='511'\tTHEN 'Palau'\n  " +
    "WHEN substr(mmsi, 1, 3)='512'\tTHEN 'New Zealand'\n  " +
    "WHEN substr(mmsi, 1, 3)='514'\tTHEN 'Cambodia'\n  " +
    "WHEN substr(mmsi, 1, 3)='515'\tTHEN 'Cambodia'\n  " +
    "WHEN substr(mmsi, 1, 3)='516'\tTHEN 'Christmas Is'\n  " +
    "WHEN substr(mmsi, 1, 3)='518'\tTHEN 'Cook Is'\n  " +
    "WHEN substr(mmsi, 1, 3)='520'\tTHEN 'Fiji'\n  " +
    "WHEN substr(mmsi, 1, 3)='523'\tTHEN 'Cocos Is'\n  " +
    "WHEN substr(mmsi, 1, 3)='525'\tTHEN 'Indonesia'\n  " +
    "WHEN substr(mmsi, 1, 3)='529'\tTHEN 'Kiribati'\n  " +
    "WHEN substr(mmsi, 1, 3)='531'\tTHEN 'Laos'\n  " +
    "WHEN substr(mmsi, 1, 3)='533'\tTHEN 'Malaysia'\n  " +
    "WHEN substr(mmsi, 1, 3)='536'\tTHEN 'N Mariana Is'\n  " +
    "WHEN substr(mmsi, 1, 3)='538'\tTHEN 'Marshall Is'\n  " +
    "WHEN substr(mmsi, 1, 3)='540'\tTHEN 'New Caledonia'\n  " +
    "WHEN substr(mmsi, 1, 3)='542'\tTHEN 'Niue'\n  " +
    "WHEN substr(mmsi, 1, 3)='544'\tTHEN 'Nauru'\n  " +
    "WHEN substr(mmsi, 1, 3)='546'\tTHEN 'French Polynesia'\n  " +
    "WHEN substr(mmsi, 1, 3)='548'\tTHEN 'Philippines'\n  " +
    "WHEN substr(mmsi, 1, 3)='553'\tTHEN 'Papua New Guinea'\n  " +
    "WHEN substr(mmsi, 1, 3)='555'\tTHEN 'Pitcairn Is'\n  " +
    "WHEN substr(mmsi, 1, 3)='557'\tTHEN 'Solomon Is'\n  " +
    "WHEN substr(mmsi, 1, 3)='559'\tTHEN 'American Samoa'\n  " +
    "WHEN substr(mmsi, 1, 3)='561'\tTHEN 'Samoa'\n  " +
    "WHEN substr(mmsi, 1, 3)='563'\tTHEN 'Singapore'\n  " +
    "WHEN substr(mmsi, 1, 3)='564'\tTHEN 'Singapore'\n  " +
    "WHEN substr(mmsi, 1, 3)='565'\tTHEN 'Singapore'\n  " +
    "WHEN substr(mmsi, 1, 3)='566'\tTHEN 'Singapore'\n  " +
    "WHEN substr(mmsi, 1, 3)='567'\tTHEN 'Thailand'\n  " +
    "WHEN substr(mmsi, 1, 3)='570'\tTHEN 'Tonga'\n  " +
    "WHEN substr(mmsi, 1, 3)='572'\tTHEN 'Tuvalu'\n  " +
    "WHEN substr(mmsi, 1, 3)='574'\tTHEN 'Vietnam'\n  " +
    "WHEN substr(mmsi, 1, 3)='576'\tTHEN 'Vanuatu'\n  " +
    "WHEN substr(mmsi, 1, 3)='577'\tTHEN 'Vanuatu'\n  " +
    "WHEN substr(mmsi, 1, 3)='578'\tTHEN 'Wallis Futuna Is'\n  " +
    "WHEN substr(mmsi, 1, 3)='601'\tTHEN 'South Africa'\n  " +
    "WHEN substr(mmsi, 1, 3)='603'\tTHEN 'Angola'\n  " +
    "WHEN substr(mmsi, 1, 3)='605'\tTHEN 'Algeria'\n  " +
    "WHEN substr(mmsi, 1, 3)='607'\tTHEN 'St Paul Amsterdam Is'\n  " +
    "WHEN substr(mmsi, 1, 3)='608'\tTHEN 'Ascension Is'\n  " +
    "WHEN substr(mmsi, 1, 3)='609'\tTHEN 'Burundi'\n  " +
    "WHEN substr(mmsi, 1, 3)='610'\tTHEN 'Benin'\n  " +
    "WHEN substr(mmsi, 1, 3)='611'\tTHEN 'Botswana'\n  " +
    "WHEN substr(mmsi, 1, 3)='612'\tTHEN 'Cen Afr Rep'\n  " +
    "WHEN substr(mmsi, 1, 3)='613'\tTHEN 'Cameroon'\n  " +
    "WHEN substr(mmsi, 1, 3)='615'\tTHEN 'Congo'\n  " +
    "WHEN substr(mmsi, 1, 3)='616'\tTHEN 'Comoros'\n  " +
    "WHEN substr(mmsi, 1, 3)='617'\tTHEN 'Cape Verde'\n  " +
    "WHEN substr(mmsi, 1, 3)='618'\tTHEN 'Antarctica'\n  " +
    "WHEN substr(mmsi, 1, 3)='619'\tTHEN 'Ivory Coast'\n  " +
    "WHEN substr(mmsi, 1, 3)='620'\tTHEN 'Comoros'\n  " +
    "WHEN substr(mmsi, 1, 3)='621'\tTHEN 'Djibouti'\n  " +
    "WHEN substr(mmsi, 1, 3)='622'\tTHEN 'Egypt'\n  " +
    "WHEN substr(mmsi, 1, 3)='624'\tTHEN 'Ethiopia'\n  " +
    "WHEN substr(mmsi, 1, 3)='625'\tTHEN 'Eritrea'\n  " +
    "WHEN substr(mmsi, 1, 3)='626'\tTHEN 'Gabon'\n  " +
    "WHEN substr(mmsi, 1, 3)='627'\tTHEN 'Ghana'\n  " +
    "WHEN substr(mmsi, 1, 3)='629'\tTHEN 'Gambia'\n  " +
    "WHEN substr(mmsi, 1, 3)='630'\tTHEN 'Guinea-Bissau'\n  " +
    "WHEN substr(mmsi, 1, 3)='631'\tTHEN 'Equ. Guinea'\n  " +
    "WHEN substr(mmsi, 1, 3)='632'\tTHEN 'Guinea'\n  " +
    "WHEN substr(mmsi, 1, 3)='633'\tTHEN 'Burkina Faso'\n  " +
    "WHEN substr(mmsi, 1, 3)='634'\tTHEN 'Kenya'\n  " +
    "WHEN substr(mmsi, 1, 3)='635'\tTHEN 'Antarctica'\n  " +
    "WHEN substr(mmsi, 1, 3)='636'\tTHEN 'Liberia'\n  " +
    "WHEN substr(mmsi, 1, 3)='637'\tTHEN 'Liberia'\n  " +
    "WHEN substr(mmsi, 1, 3)='642'\tTHEN 'Libya'\n  " +
    "WHEN substr(mmsi, 1, 3)='644'\tTHEN 'Lesotho'\n  " +
    "WHEN substr(mmsi, 1, 3)='645'\tTHEN 'Mauritius'\n  " +
    "WHEN substr(mmsi, 1, 3)='647'\tTHEN 'Madagascar'\n  " +
    "WHEN substr(mmsi, 1, 3)='649'\tTHEN 'Mali'\n  " +
    "WHEN substr(mmsi, 1, 3)='650'\tTHEN 'Mozambique'\n  " +
    "WHEN substr(mmsi, 1, 3)='654'\tTHEN 'Mauritania'\n  " +
    "WHEN substr(mmsi, 1, 3)='655'\tTHEN 'Malawi'\n  " +
    "WHEN substr(mmsi, 1, 3)='656'\tTHEN 'Niger'\n  " +
    "WHEN substr(mmsi, 1, 3)='657'\tTHEN 'Nigeria'\n  " +
    "WHEN substr(mmsi, 1, 3)='659'\tTHEN 'Namibia'\n  " +
    "WHEN substr(mmsi, 1, 3)='660'\tTHEN 'Reunion'\n  " +
    "WHEN substr(mmsi, 1, 3)='661'\tTHEN 'Rwanda'\n  " +
    "WHEN substr(mmsi, 1, 3)='662'\tTHEN 'Sudan'\n  " +
    "WHEN substr(mmsi, 1, 3)='663'\tTHEN 'Senegal'\n  " +
    "WHEN substr(mmsi, 1, 3)='664'\tTHEN 'Seychelles'\n  " +
    "WHEN substr(mmsi, 1, 3)='665'\tTHEN 'St Helena'\n  " +
    "WHEN substr(mmsi, 1, 3)='666'\tTHEN 'Somalia'\n  " +
    "WHEN substr(mmsi, 1, 3)='667'\tTHEN 'Sierra Leone'\n  " +
    "WHEN substr(mmsi, 1, 3)='668'\tTHEN 'Sao Tome Principe'\n  " +
    "WHEN substr(mmsi, 1, 3)='669'\tTHEN 'Swaziland'\n  " +
    "WHEN substr(mmsi, 1, 3)='670'\tTHEN 'Chad'\n  " +
    "WHEN substr(mmsi, 1, 3)='671'\tTHEN 'Togo'\n  " +
    "WHEN substr(mmsi, 1, 3)='672'\tTHEN 'Tunisia'\n  " +
    "WHEN substr(mmsi, 1, 3)='674'\tTHEN 'Tanzania'\n  " +
    "WHEN substr(mmsi, 1, 3)='675'\tTHEN 'Uganda'\n  " +
    "WHEN substr(mmsi, 1, 3)='676'\tTHEN 'DR Congo'\n  " +
    "WHEN substr(mmsi, 1, 3)='677'\tTHEN 'Tanzania'\n  " +
    "WHEN substr(mmsi, 1, 3)='678'\tTHEN 'Zambia'\n  " +
    "WHEN substr(mmsi, 1, 3)='679'\tTHEN 'Zimbabwe'\n  " +
    "WHEN substr(mmsi, 1, 3)='701'\tTHEN 'Argentina'\n  " +
    "WHEN substr(mmsi, 1, 3)='710'\tTHEN 'Brazil'\n  " +
    "WHEN substr(mmsi, 1, 3)='720'\tTHEN 'Bolivia'\n  " +
    "WHEN substr(mmsi, 1, 3)='725'\tTHEN 'Chile'\n  " +
    "WHEN substr(mmsi, 1, 3)='730'\tTHEN 'Colombia'\n  " +
    "WHEN substr(mmsi, 1, 3)='735'\tTHEN 'Ecuador'\n  " +
    "WHEN substr(mmsi, 1, 3)='740'\tTHEN 'UK'\n  " +
    "WHEN substr(mmsi, 1, 3)='745'\tTHEN 'Guiana'\n  " +
    "WHEN substr(mmsi, 1, 3)='750'\tTHEN 'Guyana'\n  " +
    "WHEN substr(mmsi, 1, 3)='755'\tTHEN 'Paraguay'\n  " +
    "WHEN substr(mmsi, 1, 3)='760'\tTHEN 'Peru'\n  " +
    "WHEN substr(mmsi, 1, 3)='765'\tTHEN 'Suriname'\n  " +
    "WHEN substr(mmsi, 1, 3)='770'\tTHEN 'Uruguay'\n  " +
    "WHEN substr(mmsi, 1, 3)='775'\tTHEN 'Venezuela'\n  " +
    "END as vessel_country_origin_mid from EMP").toDF()

  val df_fishing_fleet_select_country = df_fishing_fleet_country_origin.filter("vessel_country_origin_mid == 'Netherlands'")

  //save
  df_fishing_fleet_select_country.distinct().repartition(5).write.option("header","true").mode("overwrite").csv("hdfs:///user/mbis/FF_reference_frame.csv")

}